package ca.hccis.penaltytracker.entity;

import ca.hccis.penaltytracker.util.CisUtility;
import com.google.gson.Gson;

public class PenaltyTracker {

    private int id;
    private String homeTeam;
    private String awayTeam;
    private String date;
    private String penalty;
    private int quarter;
    private String penalizedTeam;
    private int offendingPlayer;
    private String ageDivision;
    private String referee;
    private double impactScore;


    // Method to gather input from user (ID is excluded as it is auto-generated by Controller)
    public void getInformation() {
        homeTeam = CisUtility.getInputStringWithValidation("Enter Home Team: ", 2, 50);
        awayTeam = CisUtility.getInputStringWithValidation("Enter Away Team: ", 2, 50);
        date = CisUtility.getInputStringWithValidation("Enter Date (yyyy-MM-dd): ", 5, 20);
        penalty = CisUtility.getInputStringWithValidation("Enter Penalty/Infraction Type: ", 2, 50);
        quarter = CisUtility.getInputIntWithValidation("Enter Quarter (1-4): ", 1, 4);
        penalizedTeam = CisUtility.getInputStringWithValidation("Enter Penalized Team: ", 2, 50);
        offendingPlayer = CisUtility.getInputIntWithValidation("Enter Offending Player Number: ", 1, 99);
        ageDivision = CisUtility.getInputStringWithValidation("Enter Age Division: ", 2, 20);
        referee = CisUtility.getInputStringWithValidation("Enter Referee Name: ", 2, 50);
        impactScore = 0.0;
    }

    // Getters and Setters

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getHomeTeam() {
        return homeTeam;
    }

    public void setHomeTeam(String homeTeam) {
        this.homeTeam = homeTeam;
    }

    public String getAwayTeam() {
        return awayTeam;
    }

    public void setAwayTeam(String awayTeam) {
        this.awayTeam = awayTeam;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getPenalty() {
        return penalty;
    }

    public void setPenalty(String penalty) {
        this.penalty = penalty;
    }

    public int getQuarter() {
        return quarter;
    }

    public void setQuarter(int quarter) {
        this.quarter = quarter;
    }

    public String getPenalizedTeam() {
        return penalizedTeam;
    }

    public void setPenalizedTeam(String penalizedTeam) {
        this.penalizedTeam = penalizedTeam;
    }

    public int getOffendingPlayer() {
        return offendingPlayer;
    }

    public void setOffendingPlayer(int offendingPlayer) {
        this.offendingPlayer = offendingPlayer;
    }

    public String getAgeDivision() {
        return ageDivision;
    }

    public void setAgeDivision(String ageDivision) {
        this.ageDivision = ageDivision;
    }

    public String getReferee() {
        return referee;
    }

    public void setReferee(String referee) {
        this.referee = referee;
    }

    public double getImpactScore() {
        return impactScore;
    }

    public void setImpactScore(double impactScore) {
        this.impactScore = impactScore;
    }

    // JSON Serialization using Gson
    public String toJson() {
        Gson gson = new Gson();
        return gson.toJson(this);
    }

    // ToString method for displaying all data
    @Override
    public String toString() {
        return "Penalty Record ID: " + id +
                "\n  Date: " + date + " | Division: " + ageDivision +
                "\n  Match: " + homeTeam + " vs " + awayTeam +
                "\n  Penalized Team: " + penalizedTeam +
                "\n  Offending Player: #" + offendingPlayer +
                "\n  Infraction: " + penalty + " (Q" + quarter + ")" +
                "\n  Official: " + referee +
                "\n  Impact Score: " + impactScore;
    }
}