-- Re-seed the TacklePenalty table with the real world sample data.
-- Run after createDatabase.sql if the table was left empty.

INSERT INTO TacklePenalty (id, homeTeam, awayTeam, date, penalty, quarter, penalizedTeam, offendingPlayer, ageDivision, referee, impactScore)
VALUES
       (1, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Mouth Guard Warning', 1, 'Saint John Falcons', 10, 'AFL', 'Terry', 0.5),
       (2, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Illegal Block in the Back', 1, 'Holland College Hurricanes', 12, 'AFL', 'Jamie', 2),
       (3, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'No Yards', 1, 'Saint John Falcons', 13, 'AFL', 'Nicholas', 1),
       (4, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Illegal Kick Out of Bounds', 1, 'Holland College Hurricanes', 82, 'AFL', 'Nathan', 1),
       (5, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Time Count Violation', 1, 'Saint John Falcons', 38, 'AFL', 'Terry', 1),
       (6, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Objectionable Conduct', 1, 'Holland College Hurricanes', 20, 'AFL', 'Chris', 2),
       (7, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Unnecessary Roughness', 1, 'Holland College Hurricanes', 66, 'AFL', 'Nathan', 5),
       (8, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Holding', 1, 'Holland College Hurricanes', 75, 'AFL', 'Terry', 2),
       (9, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Unnecessary Roughness', 1, 'Holland College Hurricanes', 20, 'AFL', 'Jamie', 5),
       (10, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Mouth Guard Warning', 2, 'Holland College Hurricanes', 81, 'AFL', 'Nicholas', 1),
       (11, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Objectionable Conduct', 2, 'Holland College Hurricanes', 24, 'AFL', 'Chris', 4),
       (12, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Unnecessary Roughness', 2, 'Saint John Falcons', 6, 'AFL', 'Nathan', 10),
       (13, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Illegal Block in the Back', 2, 'Holland College Hurricanes', 21, 'AFL', 'Chris', 4),
       (14, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Unnecessary Roughness', 2, 'Holland College Hurricanes', 36, 'AFL', 'Nicholas', 10),
       (15, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Illegal Block in the Back', 2, 'Saint John Falcons', 35, 'AFL', 'Nicholas', 4),
       (16, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Unnecessary Roughness', 2, 'Holland College Hurricanes', 35, 'AFL', 'Nicholas', 10),
       (17, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Illegal Block in the Back', 2, 'Holland College Hurricanes', 36, 'AFL', 'Jamie', 4),
       (18, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Holding', 2, 'Saint John Falcons', 37, 'AFL', 'Terry', 4),
       (19, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Unnecessary Roughness', 2, 'Holland College Hurricanes', 16, 'AFL', 'Kenny', 10),
       (20, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Unnecessary Roughness', 2, 'Saint John Falcons', 87, 'AFL', 'Nicholas', 10),
       (21, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Holding', 3, 'Holland College Hurricanes', 53, 'AFL', 'Terry', 6),
       (22, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Unnecessary Roughness', 3, 'Holland College Hurricanes', 88, 'AFL', 'Kenny', 15),
       (23, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Unnecessary Roughness', 3, 'Saint John Falcons', 16, 'AFL', 'Nicholas', 15),
       (24, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Pass Interference', 3, 'Holland College Hurricanes', 25, 'AFL', 'Chris', 9),
       (25, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Holding', 4, 'Holland College Hurricanes', 75, 'AFL', 'Terry', 8),
       (26, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Illegal Procedure', 4, 'Holland College Hurricanes', 8, 'AFL', 'Jamie', 4),
       (27, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Objectionable Conduct', 4, 'Holland College Hurricanes', 15, 'AFL', 'Nathan', 8),
       (28, 'Holland College Hurricanes', 'Saint John Falcons', '2026-09-12', 'Holding', 4, 'Holland College Hurricanes', 59, 'AFL', 'Terry', 8),
       (29, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Illegal Procedure', 1, 'Charlottetown Privateers', 68, 'U18', 'Chris', 1),
       (30, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Intentional Grounding', 1, 'Cornwall Timberwolves', 4, 'U18', 'Rob', 1),
       (31, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Objectionable Conduct', 2, 'Charlottetown Privateers', 3, 'U18', 'Terry', 4),
       (32, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Illegal Formation', 2, 'Cornwall Timberwolves', 25, 'U18', 'Mark', 2),
       (33, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Offside', 2, 'Charlottetown Privateers', 60, 'U18', 'Nicholas', 2),
       (34, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Holding', 3, 'Cornwall Timberwolves', 45, 'U18', 'Rob', 6),
       (35, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Pass Interference', 3, 'Charlottetown Privateers', 15, 'U18', 'Terry', 9),
       (36, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Tandem Buck Block', 4, 'Cornwall Timberwolves', 45, 'U18', 'Chris', 8),
       (37, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Unnecessary Roughness', 4, 'Charlottetown Privateers', 3, 'U18', 'Chris', 20),
       (38, 'Charlottetown Privateers', 'Cornwall Timberwolves', '2026-09-18', 'Pass Interference', 4, 'Cornwall Timberwolves', 21, 'U18', 'Mark', 12),
       (39, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Illegal Procedure', 1, 'Holland College Hurricanes', 65, 'AFL', 'Terry', 1),
       (40, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'No Yards', 1, 'Holland College Hurricanes', 36, 'AFL', 'Sean', 1),
       (41, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Time Count Violation', 1, 'Holland College Hurricanes', 4, 'AFL', 'Rob', 1),
       (42, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Offside', 2, 'Holland College Hurricanes', 93, 'AFL', 'Chris', 2),
       (43, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Holding', 2, 'Holland College Hurricanes', 86, 'AFL', 'Sean', 4),
       (44, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Unnecessary Roughness', 2, 'Holland College Hurricanes', 80, 'AFL', 'Paul', 10),
       (45, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Illegal Procedure', 2, 'Holland College Hurricanes', 53, 'AFL', 'Nick', 2),
       (46, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Unnecessary Roughness', 3, 'Holland College Hurricanes', 9, 'AFL', 'Nathan', 15),
       (47, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Illegal Procedure', 3, 'Holland College Hurricanes', 59, 'AFL', 'Robert', 3),
       (48, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Offside', 4, 'Holland College Hurricanes', 88, 'AFL', 'Terry', 4),
       (49, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Illegal Procedure', 4, 'Holland College Hurricanes', 63, 'AFL', 'Rob', 4),
       (50, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'No Yards', 4, 'Holland College Hurricanes', 86, 'AFL', 'Sean', 4),
       (51, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Unnecessary Roughness', 4, 'Holland College Hurricanes', 26, 'AFL', 'Sean', 20),
       (52, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Illegal Equipment', 1, 'Dalhousie Tigers', 12, 'AFL', 'Rob', 2),
       (53, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Holding', 1, 'Dalhousie Tigers', 51, 'AFL', 'Nick', 2),
       (54, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Objectionable Conduct', 1, 'Dalhousie Tigers', 3, 'AFL', 'Chris', 2),
       (55, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Offside', 2, 'Dalhousie Tigers', 51, 'AFL', 'Chris', 2),
       (56, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Unnecessary Roughness', 3, 'Dalhousie Tigers', 92, 'AFL', 'Terry', 15),
       (57, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Unnecessary Roughness', 3, 'Dalhousie Tigers', 83, 'AFL', 'Sean', 15),
       (58, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Holding', 3, 'Dalhousie Tigers', 51, 'AFL', 'Nick', 6),
       (59, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Unnecessary Roughness', 3, 'Dalhousie Tigers', 21, 'AFL', 'Sean', 15),
       (60, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Holding', 4, 'Dalhousie Tigers', 21, 'AFL', 'Rob', 8),
       (61, 'Holland College Hurricanes', 'Dalhousie Tigers', '2026-09-19', 'Offside', 4, 'Dalhousie Tigers', 92, 'AFL', 'Terry', 4),
       (62, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Offside', 1, 'Summerside Spartans', 87, 'U15', 'Jayden', 1),
       (63, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Offside', 1, 'Summerside Spartans', 15, 'U15', 'Elliott', 1),
       (64, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Illegal Block in the Back', 2, 'Summerside Spartans', 99, 'U15', 'Rob', 4),
       (65, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Offside', 2, 'Summerside Spartans', 87, 'U15', 'Jayden', 2),
       (66, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Illegal Block in the Back', 2, 'Summerside Spartans', 67, 'U15', 'Rob', 4),
       (67, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Unnecessary Roughness', 2, 'Summerside Spartans', 12, 'U15', 'Jayden', 10),
       (68, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Offside', 3, 'Summerside Spartans', 87, 'U15', 'Elliott', 3),
       (69, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Mouth Guard Warning', 3, 'Summerside Spartans', 25, 'U15', 'Mitchell', 1.5),
       (70, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Illegal Use of Hands', 3, 'Summerside Spartans', 92, 'U15', 'Mitchell', 6),
       (71, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Holding', 4, 'Summerside Spartans', 87, 'U15', 'Rob', 8),
       (72, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Mouth Guard Warning', 1, 'Souris Wildcats', 35, 'U15', 'Jayden', 0.5),
       (73, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Unnecessary Roughness', 1, 'Souris Wildcats', 34, 'U15', 'Mitchell', 5),
       (74, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Unnecessary Roughness', 2, 'Souris Wildcats', 77, 'U15', 'Elliott', 10),
       (75, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Offside', 2, 'Souris Wildcats', 52, 'U15', 'Jayden', 2),
       (76, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Holding', 2, 'Souris Wildcats', 39, 'U15', 'Mitchell', 4),
       (77, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Procedure', 3, 'Souris Wildcats', 39, 'U15', 'Jayden', 3),
       (78, 'Souris Wildcats', 'Summerside Spartans', '2026-09-20', 'Illegal Block in the Back', 4, 'Souris Wildcats', 25, 'U15', 'Rob', 8);
